### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by artemeff**
Hi!

I made some breaking changes, but now it looks more usable. What do you think?
Sorry for mess in commits, I started it as my own fork, but now I want to merge it and move to official organization on github after some improvements. Only if my code acceptable, of course :)

### CODE REVIEW

**Comment by artemeff** [comment]
@kwando I'm one of the developers who works on adapters for ROM, what we do with this PR? Merge, move to rom organization and build it as official adapter? Or I should start it myself with my code?

**Comment by kwando** [comment]
Sorry, I've missed this. Currently I'm on vacation but I'll get into this once I am home. Probably late this week.

**Comment by artemeff** [comment]
@kwando ok! :)

**Comment by solnic** [comment]
@kwando @artemeff is there any interest in resurrecting this project? I'd love to move this over to rom-rb and help building it

**Comment by kwando** [comment]
@solnic I'm not currently using it, but I'm planning to use it for elasticsearch. I'll be happy to transfer it over to rom-rb if you want.
Maybe it is better to start over from scratch with a new adapter though.

**Comment by solnic** [comment]
@kwando sounds good, let's move it then (it's got gem structure etc. already which safes time)

**Comment by kwando** [comment]
Hmm, I get ”You don’t have the permission to create repositories on rom-rb” from GitHub while trying to transfer it to rom-rb.
//Hannes N

**Comment by solnic** [comment]
@kwando I'll transfer it if you can give me access to your repo

**Pull request closed without merging**
